---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        files: \.(yaml|yml)$
        args: [--unsafe]
      - id: check-added-large-files
      - id: name-tests-test
        args:
          - "--django"
        exclude: '(^|/)tests/(?:.+/)?base\.py$'
      - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.12"
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.38.0"
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.51"
    hooks:
      - id: check-manifest
        stages: [manual]
...
