# See PEP 518 for the spec of this file
# https://www.python.org/dev/peps/pep-0518/

[build-system]
requires = ["setuptools >= 82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-acls"
version = "2.0.1"
requires-python = ">=3.12.0"
description = "NetBox plugin for managing Access Control Lists (ACLs)."
readme = { file = "README.md", content-type = "text/markdown" }
license = "Apache-2.0"
license-files = ["LICENSE.txt"]
keywords = ["netbox", "netbox-plugin"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: System :: Networking",
    "Topic :: Internet",
]

[project.optional-dependencies]
test = [
    "check-manifest==0.51",
    "pre-commit==4.6.0",
    "pytest==9.0.3",
    "ruff==0.15.14",
    "yamllint==1.38.0",
]

[project.urls]
Homepage = "https://github.com/netbox-community/netbox-acls/"
Documentation = "https://github.com/netbox-community/netbox-acls/blob/dev/README.md"
Source = "https://github.com/netbox-community/netbox-acls/"
Issues = "https://github.com/netbox-community/netbox-acls/issues"
Changelog = "https://github.com/netbox-community/netbox-acls/releases"

[tool.setuptools]
packages = ["netbox_acls"]
package-data = {"netbox_acls" = ["**/*", "templates/**"]}
