[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["netbox_acls"]
package-data = {"netbox_acls" = ["**/*", "templates/**"]}

[project]
name = "netbox-acls"
version = "1.9.1"
readme = "README.md"
requires-python = ">=3.12.0"
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    "Programming Language :: Python :: 3 :: Only",
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Intended Audience :: System Administrators',
    'Intended Audience :: Telecommunications Industry',
    'Framework :: Django',
    'Topic :: System :: Networking',
    'Topic :: Internet',
]
keywords = ["netbox", "netbox-plugin"]
license = {file = "LICENSE.txt"}

[project.optional-dependencies]
test = [
    "check-manifest==0.51",
    "pre-commit==4.5.1",
    "pytest==9.0.2",
    "ruff==0.15.6",
    "yamllint==1.38.0",
]

[project.urls]
Documentation = "https://github.com/netbox-community/netbox-acls/blob/dev/README.md"
Source = "https://github.com/netbox-community/netbox-acls/"
Tracker = "https://github.com/netbox-community/netbox-acls/issues"
