# Generated by Django 5.2.4 on 2025-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_acls", "0004_netbox_acls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslist",
            name="name",
            field=models.SlugField(max_length=500),
        ),
    ]
