---
name: CI

on:
  push:
  pull_request:

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Check Python linting & PEP8 compliance
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
        with:
          version: "0.15.6"
          args: "check --output-format=github"
          src: "netbox_acls/"

      - name: Check Python formatting
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
        with:
          version: "0.15.6"
          args: "format --check --diff"
          src: "netbox_acls/"

  test:
    runs-on: ubuntu-latest
    name: Runs plugin tests
    needs: run-lint
    steps:
      - id: git-checkout
        name: Checkout
        uses: actions/checkout@v6

      - id: docker-test
        name: Test the image
        run: ./test.sh
