---
name: Greetings

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            Thanks for opening this Issue!
            We really appreciate the feedback & testing from users like you!
          pr_message: |
            🎉 Thanks for opening this pull request!
            We really appreciate contributors like you! 🙌
